
const testimonialsData = [
    {quote: "WELL ORGANIZED, GREAT COACHES, TEACHES KIDS TECHNIQUE, IS FUN AND POSITIVE. THEY SHOW THE MOVES AND BREAKS THEM DOWN FOR THE KIDS TO LEARN AND SUCCEED. MY SON LOVES IT!", author: "Sharon D | Falcon Classes" },
    {quote: "THE INSTRUCTORS ARE SO GOOD WITH MY 3 YEAR OLD CHILD, A MORE SOCCER FOCUSED CLASS THAN OTHERS AND SHE HAD THE BEST TIME.", author: "Paula R | Blue Jay Classes"},
    {quote: "POSITIVE ENERGY AND WONDERFUL INSTRUCTORS!", author: "Amy W | Blue Jay Classes"},
    {quote: "EMIR AND TEAM WERE GREAT AT ENGAGING EVERYONE AND MAKING THE CLASS FUN WHILE TEACHING BASIC SOCCER SKILLS.", author: "Greg R | Blue Jay Classes"},
    {quote: "THE INSTRUCTORS WERE WONDERFUL MY 3 YEAR OLD HAD SUCH A GOOD TIME!! WE WILL BE BACK", author: "Paula R | Blue Jay Classes"},
  ];
  
  export default testimonialsData;
  